### ISSUE TITLE
CoM and Postural velocity reference

### ISSUE THREAD

**Issue by EnricoMingo** [robotology-playground/OpenSoT#18]
As the Cartesian Task, also CoM task and Postural task has to have the possibility to set feedforward velocities.

**Comment by arocchi** [comment]
implemented in commit 8c9c69974b5a81b8b088cd758f9fb2958a0d2cac and 9baad03fe4843f809ce2db4c6a351d208d23d4b9, needs testing

**Comment by arocchi** [comment]
implemented tests in branch test_ff, merged in devel
