### ISSUE TITLE
iDynUtils object created inside MinumEffort velocity Task 

### ISSUE THREAD

**Issue by liesrock** [robotology-playground/OpenSoT#20]
Inside the MinimumEffort class there is a ComputeGTauGradient object that when constructed creates an iDynUtils object using its default constructor(that use coman as robot): the user does not expected this behaviour because: the iDynUtils model is created without any request and if he/she is using a different robot it will not load the correct model.

**Comment by EnricoMingo** [comment]
Solved and tested in commit 30202e6fa7c9849da311adec48ff87f6238acb7d

Bella pe voi.

**Comment by EnricoMingo** [comment]
Furthermore, we should keep a copy of the model for the gradient and a reference to get at every new gradient computation the world pose.

**Comment by EnricoMingo** [comment]
Another furthermore: active_joint_mask should be taken in consideration in the computation of the gradient.

**Comment by arocchi** [comment]
Fixed in 494c47e730c28a0dcad9b1a77f0393e7970e3fc5
