### ISSUE TITLE
[SUGGESTION] Self Collision avoidance can be easily implemented as a Constraint, rather than a Task

### ISSUE THREAD

**Issue by facontidavide** [robotology-playground/OpenSoT#23]
Hi,

I noticed in recent commits that you added the skeleton of collision avoidance as a Task.

I am implemented myself such feature on my implementation of OpenSoT using CONSTRAINT instead of Task and it works pretty well. To get an idea of the concept you can look here

https://vision.in.tum.de/_media/spezial/bib/knese2014msc.pdf

Just be carefull because there is a small error in the way that the collision jacobian is calculated. I can tell you more about the latter if you are interested.

Davide

**Comment by EnricoMingo** [comment]
Hi Davide! Nice to hear news from you! Yes, we have an implementation as task based on gradient projection method. May we try to use your implementation?

**Comment by facontidavide** [comment]
Up to you, I can just tell you that it works just fine.

In short:

1) you compute the distance between two collision geometries (preferable capsules) and the closest points (P1 and P2).
2) Build a Jacobian that describes how these distance changes according to joint speed (not difficult at all, but the paper of Knese has a small inaccuracy).
3) Project the Jacobian into the segment P1P2.
4) Add this one line constraint to the matrix A (constraints) of the qpOASES solver. Note that you have an inequality constraint: the distance can increase, but there is a limit to how much id decrease (such limit is the distance norm() ).
5) These constraint (one for each capsule pair to be checked) shall be added to each of the task of the SoT.

As I said, it works great for me and took me only 2-3 days to implement

**Comment by EnricoMingo** [comment]
Is the code for the self-collision avoidance available somewhere?

**Comment by facontidavide** [comment]
Unfortunately I had to implement my own SoT in Java and using different kinematic libraries (no Yarp), so I wrote the code from scratch and sharing that mess won't help you.

Anyway you can follow the description from chapter 3 of the Knese thesis. Just be aware on section 3.2.1, because there is an error.

The matrix to be projected (equations 3.20 and 3.21) is NOT just J(p1,q) but 

( J(p1,q) - J(p2,q) )

A part from that, it works as advertised,

For capsule distance query, I started from the code here (refactored to Java).

http://geomalgorithms.com/a07-_distance.html

To create the capsules you might want to look at this https://github.com/roboptim/roboptim-capsule , but I did it by hand.

**Comment by arocchi** [comment]
Done!
We use FCL for distance computation (waiting for moveit and the ros stack to support capsules natively...), at the moment there is just a narrow phase check (i.e. O(n^2))
Some tools developed in the process:
https://github.com/arocchi/robot_capsule_generator - creates a .urdf file where all meshes are substituted with cylinders representing minimum volume bounding capsules (using roboptim-capsule) and a .rviz file which is a urdf where the minimum bounding capsules are actuallty a mix of cylinders and spheres (for visualization)
https://github.com/arocchi/moveit_compute_default_collisions - command line utility to generate the Allowed Collision Matrix automatically (using  moveit_setup_assistant libraries)
