### ISSUE TITLE
OpenSoT/qpOases is spamming $HOME with m-files

### ISSUE THREAD

**Issue by geez0x1** [robotology-playground/OpenSoT#27]
Running DRC tasks that use OpenSoT results in my $HOME directory being filled with m-files for debugging. This appears to be default behaviour, which imho should be off by default.

**Comment by EnricoMingo** [comment]
Could be assigned to me pls? Thx
Il 07/apr/2015 11:15, "geez0x1" <notifications@github.com> ha scritto:

**Comment by geez0x1** [comment]
I don't think I'm allowed to do that..

**Comment by EnricoMingo** [comment]
Ok, I'll do it asap
Il 07/apr/2015 11:47, "geez0x1" <notifications@github.com> ha scritto:

**Comment by EnricoMingo** [comment]
Should be solved in commit 9dabb1841d56a8539e516ea22a74b3b7252956ad in devel branch.
Need to be tested. I'll close.
