### ISSUE TITLE
[devel] MinVelocity Task

### ISSUE THREAD

**Issue by EnricoMingo** [robotology-playground/OpenSoT#30]
A minimum velocity task can be easily implemented starting from the postural task (using the actual q as qd so that b = 0). Furthermore there should be the possibility to enable a sort of special version of this task considering to use the M matrix as gain: this basically let minimize the kinetic energy:

dq = argmin ||dqMdq||

**Comment by arocchi** [comment]
started working on it on branch minimum_velocity

**Comment by arocchi** [comment]
done: automatic weighting by the inertia matrix is still missing

**Comment by EnricoMingo** [comment]
I don't think is needed the automatic weighting by inertia matrix. Maybe we can think to remove this task since now can be easily implemented setting ```lambda = 0``` in the postural?

**Comment by EnricoMingo** [comment]
We keep the min velocity task as it is.
